package parser

import (
	log "github.com/Sirupsen/logrus"

	"encoding/json"
	"fmt"

	"github.com/lepinkainen/instafetch/worker"
)

var (
	instagramStreamURL = "https://www.instagram.com/%s/?__a=1" // completed with username
)

// API Structs autogenerated with https://github.com/mohae/json2go/tree/master/cmd/json2go

// InstagramAPI is a reply to the main page query
type InstagramAPI struct {
	LoggingPageID string `json:"logging_page_id"`
	User          `json:"user"`
}

func getNextPageInfo(response InstagramAPI) (string, string) {
	if !response.User.Media.PageInfo.HasNextPage {
		return "", ""
	}

	var id = response.User.ID
	var endCursor = response.User.Media.PageInfo.EndCursor

	return id, endCursor
}

// the first page is a bit different from the other pages
func getFirstPage(userName string) InstagramAPI {
	myLogger := log.WithField("module", "stream")
	var url = fmt.Sprintf(instagramStreamURL, userName)

	// interface to hold the instagram JSON
	var response InstagramAPI

	data, err := worker.GetPage(url)
	if err != nil {
		myLogger.Errorln("Error fetching page", err.Error())
		return response
	}

	myLogger.Debugf("Page for %s fetched", userName)

	// unmarshal the JSON to the interface
	err = json.Unmarshal(data, &response)
	if err != nil {
		myLogger.Errorln("Error unmashaling JSON", err.Error())
		fmt.Println(string(data))
		return response
	}

	myLogger.Debugf("Data for %s unmarshaled", userName)

	return response
}

func parseFirstPage(res InstagramAPI, urls chan<- string) {
	myLogger := log.WithField("module", "stream")

	// get media urls according to type
	for _, media := range res.User.Media.Nodess {
		switch shortcode := media.Typename; shortcode {
		case "GraphVideo":
			getVideoURL(media.Code, urls)
		case "GraphSidecar":
			getSidecarURLs(media.Code, urls)
		case "GraphImage":
			urls <- media.DisplaySrc
			//getImageURL(media.Code, urls)
		default:
			myLogger.Errorf("Unknown media type: '%v'", media.Typename)
		}
	}
}

// MediaURLs returns direct links to all media on an users stream
func MediaURLs(userName string, urls chan<- string) {
	myLogger := log.WithField("module", "stream")
	res := getFirstPage(userName)

	parseFirstPage(res, urls)

	id, endCursor := getNextPageInfo(res)

	page := 1

	for endCursor != "" {
		myLogger.Infof("Parsed page %d for %s", page, userName)
		endCursor = parseNextPage(id, endCursor, urls)
		page = page + 1
	}
}
